version: '3.8'

services:
  tkr-news-gather:
    build: .
    ports:
      - "8000:8000"
    environment:
      - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY}
      - ANTHROPIC_MODEL=${ANTHROPIC_MODEL:-claude-3-haiku-20240307}
      - LLM_TEMP=${LLM_TEMP:-0.7}
      - LLM_MAX_TOKENS=${LLM_MAX_TOKENS:-2000}
      - SUPABASE_URL=${SUPABASE_URL}
      - SUPABASE_ANON_KEY=${SUPABASE_ANON_KEY}
      - LOG_LEVEL=${LOG_LEVEL:-INFO}
      - DEFAULT_NEWS_LIMIT=${DEFAULT_NEWS_LIMIT:-10}
      - SCRAPE_TIMEOUT=${SCRAPE_TIMEOUT:-30}
      - MAX_CONCURRENT_SCRAPES=${MAX_CONCURRENT_SCRAPES:-10}
      - API_HOST=0.0.0.0
      - API_PORT=8000
    volumes:
      - ./.env:/app/.env:ro
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "python", "-c", "import requests; requests.get('http://localhost:8000/health')"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s